project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  google-analytics: "GT-KFT2NXK"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating
  comments:
    giscus:
      repo: ashantanu/tech-blog
      repo-id: R_kgDOKARy6w
      category: General
      category-id: DIC_kwDOKARy684CYV2A
      reactions-enabled: true
      loading: lazy

metadata-files: [nbdev.yml, sidebar.yml]
