# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tech-blog',
                'doc_host': 'https://ashantanu.github.io',
                'git_url': 'https://github.com/ashantanu/tech-blog',
                'lib_path': 'tech_blog'},
  'syms': {'tech_blog.core': {'tech_blog.core.foo': ('core.html#foo', 'tech_blog/core.py')}}}
